module.exports = {
  title: "Yongseok",
  description: "Hello Yongseok",
  author: "Yongseok",
  siteUrl: "https://Yongseokblog.com",
  links: {
    github: "https://github.com/Yongseok-2",
    linkedIn: "https://linkedin.com",
    facebook: "https://www.facebook.com",
    twitter: "https://twitter.com",
    x: "https://x.com",
    instagram: "https://www.instagram.com",
    medium: "https://medium.com",
    blogger: "https://blogger.com",
    email: "8465867@naver.com",
    resume: "https://Yongseok-2.blog",
    link: "https://Yongseok-2.blog",
  },
  useAbout: true,
  // See https://giscus.app/
  giscus: {
    repo: "Yongseok-2/Yongseok-2.github.io",
    repoId: "MDEwOlJlcG9zaXRvcnkzNjk4NjMzNTg=",
    category: "Comments",
    categoryId: "DIC_kwDOFguqvs4ChwGy",
    mapping: "pathname",
    strict: "0",
    reactionsEnabled: "1",
    inputPosition: "bottom",
    lang: "en",
  },
}
